server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    druid:
      # 监控统计用的stat,防御sql注入的wall,日志用的slf4j
      filter: stat,wall,slf4j
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 100
      # 获取连接最大等待时间，
      max-wait: 10000
      # 配置多久时间检测一次需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小的生存时间
      min-evictable-idle-time-millis: 30000
      # 验证连接有效与否的SQL
      validation-query: SELECT 1 FROM DUAL
      #
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 打开PSCache,并指定每个连接中的PSCache大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20


  #配置rabbitMq 服务器
#  rabbitmq:
#    host: 192.168.189.130
#    port: 5672
#    username: admin
#    password: admin
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: /

    #消息确认配置项
    #确认消息已发送到交换机(Exchange)
    #publisher-confirms: true 该配置是springboot版本为 2.1.7.RELEASE
#    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
#    publisher-returns: true

dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-web   #定义消费者名称
  registry:               #注册中心地址
    address: zookeeper://192.168.189.130:21811

  